### ISSUE TITLE
Quick Sort in Python

### ISSUE THREAD

**Issue by deepansha-singh** [CodeChefMUST/Algorithms#129]
# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. In the `Sorting` directory, and navigate to the sub-directory `Quick Sort`.
2. Create the `Python` directory in the `Quick Sort` directory.
3. Create the file `QuickSort.py`.

Here's how the final structure should look like:
- Sorting
    - Quick Sort
        - Algorithm.md
        - C++
        - Python
              - QuickSort.py

## Before you create a pull request, if you observe that the folder Quick Sort has already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts.

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by koffy1** [comment]
@deepansha-singh Assign this to me

**Comment by priyanshu688** [comment]
@deepansha-singh I have added the Quick Sort program in Python language as per your required directory. Please review this PR - https://github.com/CodeChefMUST/Algorithms/commit/8702e001dd8e5ac8f7916bab4731002e341788f4

**Comment by deepansha-singh** [comment]
Assigned to @koffy1 
Kindly go through the guidelines. Looking forward to your contribution!

@priyanshu688 I would like to bring to your notice that you need to get an issue assigned to yourself before working on it, according to our repo guidelines :)
Please go through the existing issues that need help and you'd like to work on, or even feel free to create your own.
